// packages/remote-react/src/App.tsx
import { useState, useEffect } from 'react';
import { createRoot } from 'react-dom/client';

const s = {
  widget: { background: 'linear-gradient(135deg, #0f1729 0%, #1a2744 100%)', border: '1px solid rgba(97,218,251,0.2)', borderRadius: '12px', padding: '24px', color: '#e4e6f0', fontFamily: "-apple-system, sans-serif" },
  header: { display: 'flex' as const, alignItems: 'center' as const, gap: '12px', marginBottom: '12px' },
  icon: { fontSize: '24px', color: '#61dafb' },
  title: { fontSize: '20px', fontWeight: 700, margin: 0 },
  desc: { color: '#8b8fa3', fontSize: '14px', marginBottom: '20px', lineHeight: 1.5 },
  grid: { display: 'grid' as const, gridTemplateColumns: 'repeat(3,1fr)', gap: '12px', marginBottom: '20px' },
  stat: { background: 'rgba(0,0,0,0.2)', borderRadius: '8px', padding: '16px', textAlign: 'center' as const },
  num: { display: 'block', fontSize: '28px', fontWeight: 800, color: '#61dafb' },
  lbl: { display: 'block', fontSize: '11px', color: '#8b8fa3', marginTop: '4px', textTransform: 'uppercase' as const, letterSpacing: '0.05em' },
  btn: { width: '100%', padding: '12px', border: 'none', borderRadius: '8px', background: '#0ea5e9', color: 'white', fontSize: '14px', fontWeight: 600, cursor: 'pointer' },
} as const;

export default function App() {
  const [count, setCount] = useState(0);
  const [renders, setRenders] = useState(0);

  useEffect(() => {
    setRenders((r) => r + 1);
    console.log('[remote-react] App mounted via Vite Federation');
  }, []);

  return (
    <div style={s.widget}>
      <div style={s.header}>
        <span style={s.icon}>⚛</span>
        <h3 style={s.title}>React Remote Widget</h3>
      </div>
      <p style={s.desc}>This component is served from <strong>remote-react</strong> (port 4202) via Vite Module Federation.</p>
      <div style={s.grid}>
        <div style={s.stat}><span style={s.num}>{count}</span><span style={s.lbl}>Counter</span></div>
        <div style={s.stat}><span style={{...s.num, color:'#38bdf8'}}>v19</span><span style={s.lbl}>React</span></div>
        <div style={s.stat}><span style={s.num}>{renders}</span><span style={s.lbl}>Renders</span></div>
      </div>
      <button style={s.btn} onClick={() => setCount((c) => c + 1)}>Increment Counter</button>
    </div>
  );
}

export function mount(container: HTMLElement): () => void {
  const root = createRoot(container);
  root.render(<App />);
  return () => root.unmount();
}

// packages/remote-vue/src/App.vue
<script setup lang="ts">
import { ref, onMounted } from 'vue';

const count = ref(0);
const message = ref('Hello from Vue!');

onMounted(() => { console.log('[remote-vue] App mounted via Vite Federation'); });
function increment() { count.value++; }
</script>

<template>
  <div class="widget">
    <div class="widget-header">
      <span class="widget-icon">◈</span>
      <h3>Vue Remote Widget</h3>
    </div>
    <p class="widget-description">
      This component is served from <strong>remote-vue</strong> (port 4203) via Vite Module Federation.
    </p>
    <div class="widget-stats">
      <div class="widget-stat"><span class="stat-number">{{ count }}</span><span class="stat-label">Counter</span></div>
      <div class="widget-stat"><span class="stat-number vue-version">v3</span><span class="stat-label">Vue</span></div>
      <div class="widget-stat"><span class="stat-number">{{ message.length }}</span><span class="stat-label">Msg Len</span></div>
    </div>
    <input v-model="message" class="widget-input" placeholder="Type a message..." />
    <button class="widget-btn" @click="increment">Increment Counter</button>
  </div>
</template>

<style scoped>
.widget { background: linear-gradient(135deg, #0f1f17 0%, #1a3d2e 100%); border: 1px solid rgba(79,192,141,0.2); border-radius: 12px; padding: 24px; color: #e4e6f0; font-family: -apple-system, sans-serif; }
.widget-header { display: flex; align-items: center; gap: 12px; margin-bottom: 12px; }
.widget-icon { font-size: 24px; color: #4fc08d; }
h3 { font-size: 20px; font-weight: 700; margin: 0; }
.widget-description { color: #8b8fa3; font-size: 14px; margin-bottom: 20px; line-height: 1.5; }
.widget-stats { display: grid; grid-template-columns: repeat(3,1fr); gap: 12px; margin-bottom: 20px; }
.widget-stat { background: rgba(0,0,0,0.2); border-radius: 8px; padding: 16px; text-align: center; }
.stat-number { display: block; font-size: 28px; font-weight: 800; color: #4fc08d; }
.stat-label { display: block; font-size: 11px; color: #8b8fa3; margin-top: 4px; text-transform: uppercase; letter-spacing: 0.05em; }
.vue-version { color: #6ee7b7; }
.widget-input { width: 100%; padding: 10px 14px; border: 1px solid rgba(79,192,141,0.3); border-radius: 8px; background: rgba(0,0,0,0.2); color: #e4e6f0; font-size: 14px; margin-bottom: 12px; outline: none; box-sizing: border-box; }
.widget-input:focus { border-color: #4fc08d; }
.widget-btn { width: 100%; padding: 12px; border: none; border-radius: 8px; background: #059669; color: white; font-size: 14px; font-weight: 600; cursor: pointer; transition: background 0.2s; }
.widget-btn:hover { background: #047857; }
</style>
